# Generated by Django 5.2.5 on 2026-08-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_organization_auditlog_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcase',
            options={'ordering': ['-report__risk_score', '-created_at']},
        ),
    ]
