FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["gunicorn","safeconnect.wsgi:application","--bind","0.0.0.0:8000","--workers","3"]
